apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wik-tp4
  labels:
    app: wik-tp4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wik-tp4
  template:
    metadata:
      labels:
        app: wik-tp4
    spec:
      containers:
      - name: wik-tp4
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 80
        env:
        - name: PING_LISTEN_PORT
          value: "80"

